### PR TITLE
Update "Motivation" section in README.md

### PR DESCRIPTION
**Pull request by Aneal-Sharma**
The following changes make the "Motivation" section more concise.

### CODE REVIEW

**Comment by iusehooks** [comment]
What about the rest of the docs do you find it good?

**Comment by Aneal-Sharma** [comment]
I will look through the rest of the document

**Comment by iusehooks** [comment]
Would you resolve the conflicts?

**Comment by iusehooks** [comment]
The Motivation Section has been edited in another PR [#4](https://github.com/iusehooks/redhooks/pull/4)

**Pull request closed without merging**
